### ISSUE TITLE
AboutMe Description in the Profile not long enough

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#11]
Today I wanted to fill in the AboutMe description in the admin user profile, but it does not add many words. Maybe it was not planned, but can the description be realized in more words?

Thanks in advance. Otherwise there is the error after sending the profile.

**Comment by KarlBrittain** [comment]
This 'bug' is not a LayerBB bug, however this has to do with MySQL. It is limited by the database field type 'VARCHAR255' thus limiting the field to 255 characters.
