### ISSUE TITLE
Bigger Font like Headings in Topics do not work

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#12]
Hi Andy,

can you please check the font size change in the BBCode editor in the topics, because it does not seem to work.

Example Topis as under https://layerbb.liebrechts-portfolio.de/thread.php/yaf_forum_liebrechts_portfolio_de_board_f_uuml_r_opensource_apps_bloggen_projekterviews_und_mehr.4

Wanted Big Font to have the heading, but after submitting the topic, the font was not enlarged. Bigger font I took with the BBCode editor tool button.

That should still be checked.

Thanks in Advance.

**Comment by ghost** [comment]
I’ll take a look at this when I can, I’ve been getting all sorts of issues with the editor.

**Comment by KarlBrittain** [comment]
We located the bug within. To fix this, we have renamed 'font size' to 'Headings'.

**Comment by ghost** [comment]
Thank you very much for fixing and I think that it will be available at the latest in the final version. I tested it again in beta 4, unfortunately without success. But nice that you have dedicated yourself to the bug.

**Comment by KarlBrittain** [comment]
Hi Alex,

That is correct, any bug fixes or enhancements we make, will become public in the next available version. We plan to release our next version within the next week or so.
