### ISSUE TITLE
Forum Rules & Offline Message

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#13]
### Expected Behaviour

When I post HTML code, for example `<a href="www.layerbb.com">LayerBB</a>` it should display a Hyperlinked 'LayerBB'

### Actual Behaviour

In fact, it displays the HTML code, rather than displaying the hyperlink. ([LayerBB](http://layerbb.com))

### Steps to Reproduce Issue

Edit the Forum Rules & Offline Message with the example text and hit save.

### Server Environment (PHP, MySQL, Apache Version and Operating System)

Not required due the bug being on the Dev Forum & Public Forum.

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Hyperlinks are not supported in forum rules, but they do correctly show in the offline message.

Many Thanks,
LayerBB Development Team
