### ISSUE TITLE
LayerBB 1.0.0 RC1 New Installation: In The Frontend Template not exist

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#15]
### Expected Behaviour

Hi Andy,

with me is the same problem after all LayerBB updates, so that the template can not be found.

I have now made a complete new installation with LayerBB 1.0.0 RC1 and the bug still exists.

What else can I do or why do my Centos 7.4 hosting or the MariaDB databases behave like this?

Thanks in Advance.

### Steps to Reproduce Issue

Fresh Install of LayerBB 1.0.0 RC1 under Centos 7.4 with MariaDB as Database Engine

### Server Environment (PHP, MySQL, Apache Version and Operating System)

All the latest Versions of PHP 7.1-7.2, MariaDB 10.2, Apache, Centos 7.4 OS/Linux

**Comment by KarlBrittain** [comment]
Hi Alex,

Please could you resend your server login details to ***************** and we will submit the fix again.

Many thanks,
Karl

**Comment by AndyRixon** [comment]
I've come to the conclusion that this is an on going issue with Plesk/MariaDB.

Due to the way Plesk configures services such as PHP and MariaDB, we will no longer officially support MariaDB.

I have got a second opinion from @KarlBrittain regarding this and he is in agreement with this.

For the time being, I have managed to manually install your LayerBB 1.0.0-RC1 for you.

We will no longer provide help regarding a similar issue to this in the future.

All language changes I made in your Plesk, have been returned back to Default/GERMAN.

**Comment by ghost** [comment]
Thank you! Then it's a shame and I will have no choice but to dispense with all LayerBB updates. Let's see if my forum can survive like this. I am very hopeful. Unfortunately, I have no second hosting with MySQL 5.7 ect.pp.

## Update: 01.01.2018 00:38 am

I want to use the LayerBB forum in the near and far future including all updates. Therefore, I will take a second hosting the German hoster Uberspace in purchasing. I just have to pay 10 euros a month for it. I can afford that and if MariaDB does not play along with any forum app, I can install it on Uberspace Hosting.

I really hope they work there with MySQL 5.7. Should actually be present.

**Comment by AndyRixon** [comment]
Most if not all will work with MySQL 5.7 with no issues.

We will continue to look into MariaDB, but we are only a very small team with limited time and resources to be able to fully test everything.

Ultimately though, at this stage, MariaDB won't be supported. This is not us saying that it will never be supported though.

**Comment by AndyRixon** [comment]
Our of curiosity, I've just done a test install under CentOS 7 (64bit), PHP 7.1.12, MariaDB 10.2.3 and Apache 2.4 - and I was getting issues with it installing until I disabled SElinux.

Could you try [disabling SElinux](https://www.centos.org/docs/5/html/5.1/Deployment_Guide/sec-sel-enable-disable.html), and trying again.

Once I disabled SElinux, I was able to go through the installation perfectly fine, if  you still get an issue then it has to do with something in your Plesk Server configuration somewhere.

**Comment by ghost** [comment]
OK, Thanks for the Hints.

With me selinux is disabled. Hm...strange!

**Comment by ghost** [comment]
Is very interesting and probably it was under Centos 7.4 really at the Plesk Config. I now claim second hosting with also MariaDB 10.1

SSH check was as follows:

mysql --version
mysql Ver 15.1 Distrib 10.1.24-MariaDB, for Linux (x86_64) using readline 5.1

And LayerBB was successfully installed. That is very good, because then I can take all the following updates.

**Comment by AndyRixon** [comment]
So it seems to be an issue with Plesk then, not MariaDB as we originally thought.
