### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#16]
### Expected Behaviour

When you use the Facebook Login/Registration, it should log you in.

### Actual Behaviour

Missing the registration, but the login fails and returns the URL https://forum.layerbb.com/forum.php#_=_

### Steps to Reproduce Issue

Enable the Facebook Login, then try logging in.

### Server Environment (PHP, MySQL, Apache Version and Operating System)

N/A

**Comment by AndyRixon** [comment]
Due to being in an early stage of development, this feature will not work.
