### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#18]
### Expected Behaviour

When changing the font size within the text editor, the font size should be shown on public and the editor.

### Actual Behaviour

The font sizing isn't showing correctly on the public (view).

### Steps to Reproduce Issue

Try to change the font size.

### Server Environment (PHP, MySQL, Apache Version and Operating System)

N/A

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
