### ISSUE TITLE
LayerBB 1.0.0 Attachments Error on Topics

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#19]
### Expected Behaviour

If I want to add attachments to the topic, I get the following error. Please take a look at the screenshot below. Thank you.

### Actual Behaviour

![layerbb-attachments-error](https://user-images.githubusercontent.com/7885632/34909429-1cd2699c-f8a1-11e7-8b9b-42c83ef99dee.jpg)

### Steps to Reproduce Issue

After the installation or the update to LayerBB 1.0.0 it happens.

### Server Environment (PHP, MySQL, Apache Version and Operating System)

Shared Hosting, Ubuntu, MariaDB 10.0 with redline as MySQL, PHP 7.1

**Comment by AndyRixon** [comment]
Not a bug to be honest, it's just a feature that hasn't been added because to be honest, we forgot about. It will be there soon though.

**Comment by ghost** [comment]
OK, Thanks!!
