### ISSUE TITLE
Update to LayerBB 1.0.1 - Error >> Template not exist

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#20]
### Expected Behaviour

Very sad, but after the update to LayerBB v1.0.1 I will not see a template in the frontend.

Again with MariaDB 10.1 on shared hosting.

How can I now work with this app otherwise, because I do not have pure MySQL as Database Engine in the portfolio.

### Steps to Reproduce Issue

Update to LayerBB v1.0.1

### Server Environment (PHP, MySQL, Apache Version and Operating System)

Ubuntu, PHP 7.1, MariaDB 10.1 on Shared Hosting

**Comment by AndyRixon** [comment]
Could you tell me what value is in the site_theme column within the generic table, also verify that the theme exists in the themes table.

**Comment by ghost** [comment]
This is "1".

Is This correct?

**Comment by AndyRixon** [comment]
If that is for site_theme in generic, then yes that is how it should be. 
Could you tell me if the theme is in the themes table.

**Comment by ghost** [comment]
![layerbb-theme-table](https://user-images.githubusercontent.com/7885632/34963069-ceb9befc-fa46-11e7-8f8f-ddf169d86969.jpg)

**Comment by AndyRixon** [comment]
Any error_log files?
If so, could you provide the content of these files, using something like PasteBin

**Comment by ghost** [comment]
I only have the one log files on shared hosting. These are regenerated every night at 04:18. I have to be patient then, otherwise in cPanel no other files or the errors of today are not displayed.

Let's wait until tonight. Tomorrow I may be able to tell you more.

Thank you.

**Comment by AndyRixon** [comment]
These error_log files are generated upon a php error, not by cron.

Please paste the contents of [this URL](https://pastebin.com/raw/hgzHBvjn) into that theme_json_data column on the database, it should then work.

Let me know the result.

**Comment by ghost** [comment]
Yes, my Problem is solved 👍 😺

**Comment by AndyRixon** [comment]
Awesome.
Somewhere down the line the update script isn't updating the json data for the theme, we shall take a look.
