### ISSUE TITLE
May I forked the LayerBB Repo to Gitlab Server

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#21]
### Expected Behaviour

Hi Developers,

I have my own Gitlab server at http://gitlab.liebrechts-portfolio.de and can import repositories from Githut etc. May I import the layerBB repo to Gitlab Server.

I would like to write German details and show the readers the forum or bring something closer. So LayerBB gains notoriety and maybe it uses someone from my blogger circles.

Thanks in Advance.

**Comment by AndyRixon** [comment]
Is this so that you can create a language for LayerBB?

**Comment by ghost** [comment]
I would like to try it.

I understand it correctly and I've just opened english.php. All I have to do is translate the English into German and rename the file to german.php?

Is this correct or does it require special technical knowledge?

**Comment by AndyRixon** [comment]
You are able to do this without forking it, but yes you are correct on how to do it.
You may fork it to a private GitLab, however it MUST be private and does not allow public access.

**Comment by ghost** [comment]
Okay, then I leave it with the fork. I'll try to the translation of it and then test the language in my forum.

Can I then offer this German language in my Github account in the new repo? So anyone can download and use it.

Thank you.

**Comment by AndyRixon** [comment]
Sure. I will create a node on LayerBB Forum so that you can advertise the language pack there.

**Comment by ghost** [comment]
Thanks for This! I am currently busy translating and it is a huge pleasure 😄

**Comment by ghost** [comment]
I have now translated the file english.php except the states. I can do that later. But unfortunately if I activate "German" in the backend, the forum is not available.

In german.php I used HTML for German umlauts. I know it's a php file and so my question is if that works? Not really, apparently.
