### ISSUE TITLE
Forum Node Permissions

### ISSUE THREAD

**Issue by AndyRixon** [AndyRixon/LayerBB#23]
### Expected Behaviour
When unticking "Guests" in node permissions you would expect it to stay unticked.
### Actual Behaviour
Should stay unticked when unticked
### Steps to Reproduce Issue
Untick "Guest" in Allowed Usergroups when editing a Forum Node.
### Server Environment (PHP, MySQL, Apache Version and Operating System)
N/A (Found it on the official forums)

**Comment by hiddenbanana** [comment]
Category usergroup "Guest" missing with ID of "0". 

Issue will be resolved with next release.
