### ISSUE TITLE
Sort user 'Guest' within AdminCP

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#24]
### Expected Behaviour

When selecting 'Guests', it should display the users who have the Guest usergroup assigned.

### Actual Behaviour

Displays all usergroups.

### Steps to Reproduce Issue

Select guests.

### Server Environment (PHP, MySQL, Apache Version and Operating System)

N/A

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
