### ISSUE TITLE
Issues Found by Softaculous Team

### ISSUE THREAD

**Issue by AndyRixon** [AndyRixon/LayerBB#25]
This is the email I have received.

> Hi Andy,
>
>Getting Following errors in LayerBB 1.0.4
>
>1. On adding new user
>Unhandled Exception.
>
>SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check >the manual that corresponds to your MySQL server version for the right syntax to use near '> 0' at line >1
>You can find the error back in the log.
>
>2. On adding new user category
>
>Notice: Undefined variable: return in admin/new_category.php on line 27
>
>3. On adding new Node
>
>Notice: Undefined variable: return in admin/new_node.php on line 43
>
>4. Application menu is not working in MAIN NAVIGATION

**Comment by AndyRixon** [comment]
I have fixed points 2 & 3, and explain that with point 4, the menu item still shows but won't drop down even if there are no applications installed, this needs to be reworked and either not so the menu item at all, or add a no apps installed item.

As for point 1, I am waiting for further information regarding how the issue was produced.

**Comment by AndyRixon** [comment]
I've done a bit more digging and beleive I have fixed point 1 too, waiting for more information.

**Comment by AndyRixon** [comment]
Now added check if any applications are installed, if not show No Apps Installed menu item with a link to Manage Applications page.

**Comment by GaneshKandu** [comment]
```php
function list_groups()
{
    global $MYSQL;
    $query = $MYSQL->query('SELECT * FROM {prefix}usergroups > 0');
    $return = '';
    foreach ($query as $s) {
        $checked = ($s['id'] == $check) ? ' selected' : '';
        $return .= '<option value="' . $s['id'] . '"' . $checked . '>' . $s['group_name'] . '</option>';
    }
    return $return;
}
```

```SELECT * FROM {prefix}usergroups > 0```  sql query is wrong
