### ISSUE TITLE
Missing Space

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#26]
### Expected Behaviour

In between the 'Feature Suggestion' and the Thread title, should have a space

### Actual Behaviour

![screen shot 2018-02-08 at 21 29 28](https://user-images.githubusercontent.com/34407166/35999274-2a3f939a-0d17-11e8-9bee-ba3616cc07b0.png)

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
