### ISSUE TITLE
Roles issue - urgent

### ISSUE THREAD

**Issue by JacappPublishing** [AndyRixon/LayerBB#27]
### Expected Behaviour
Mod (lower rank) is not able to ban a higher rank (Admin)

### Actual Behaviour
Mod (lower rank) is able to ban a higher rank (Admin) - very forum breaking.

### Steps to Reproduce Issue
Try to ban an admin (Higher role) while having a lower role (Mod)

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
