### ISSUE TITLE
Password recovery email not using SMTP settings

### ISSUE THREAD

**Issue by bloopkins** [AndyRixon/LayerBB#28]
### Expected Behaviour
Sending password recovery email through SMTP
### Actual Behaviour
Sending password recovery email through my personal email
### Steps to Reproduce Issue
Try to recover the password
### Server Environment (PHP, MySQL, Apache Version and Operating System)
Shared hosting, latest version of all of these OS is unknown

**Comment by AndyRixon** [comment]
The SMTP settings haven't worked for a long time, we haven't been able to get it work correctly, it is being removed from the next version.
