### ISSUE TITLE
Signature Page doesn't automatically reload and show new changes.

### ISSUE THREAD

**Issue by cpkOfficial** [AndyRixon/LayerBB#30]
### Expected Behaviour
Once setting your signature on your profile the page should automatically reload and show the changes made to the signature.
### Actual Behaviour
After setting signature in the textbox and clicking "Save Changes" the page reloads and shows the old set Signature instead of the updated one.
### Steps to Reproduce Issue
1. Clicked Signature Link
2. Set Signature In Textbox
3. Clicked Save Changes.
4. Page reloaded and Showed old set Signature instead of updating automatically to the new one. Resulting you to need to reload the page manually to see the set changes.
### Server Environment (PHP, MySQL, Apache Version and Operating System)
As i'm using a Webhost I don't have much information other then my own personal system.
Windows 10

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
