### ISSUE TITLE
Personal Details 'About You' editor.

### ISSUE THREAD

**Issue by KarlBrittain** [AndyRixon/LayerBB#32]
### Expected Behaviour

Editor should should display formatted text when saved.

### Actual Behaviour

Upon saving the contents of the editor reverts the changes, so I'm guessing the database is not allowing the formatted text and only allowing plain text format..

### Steps to Reproduce Issue

Edit your profile 

### Server Environment (PHP, MySQL, Apache Version and Operating System)

N/A

**Comment by KarlBrittain** [comment]
After further investigation, this issue is very similar to issue #30 and is NOT a database issue as first thought.

**Comment by AndyRixon** [comment]
Thank you for submitting this issue to us.
I can confirm that this has been **FIXED** and will be available in our next release.

Many Thanks,
LayerBB Development Team
