### ISSUE TITLE
Guest users can see all thread and users // but they are not supposed to

### ISSUE THREAD

**Issue by overcrash66** [AndyRixon/LayerBB#48]
### Steps to Reproduce Issue:
1-As anonymous user (or let's call it guest) 
2-Go to: https://forum.layerbb.com/search.php
3-In the Search box tip %
4-Click search

### Server Environment (PHP, MySQL, Apache Version and Operating System):
current version

**Comment by AndyRixon** [comment]
I can see your point on this one, however it is only in the search results that the title is revealed to all users including guests, upon clicking on the post however you will be greeted by a sign in page.

I will say this though, the search feature is in major need of refinement, which will be done in a future version.
