### ISSUE TITLE
XSS Injection

### ISSUE THREAD

**Issue by overcrash66** [AndyRixon/LayerBB#49]
### Steps to Reproduce Issue:
1-Create a new thread (or reply to a post).
2-Click insert an image.
3-On the link copy past this:
`<img src="http://url.to.file.which/not.exist" onerror=alert(document.cookie);>`
4-Click insert.

### Server Environment (PHP, MySQL, Apache Version and Operating System):
Current version.

**Comment by AndyRixon** [comment]
Duplicate of #46 

I think these two fall into the same sort of thing.
