### ISSUE TITLE
Any user is able to Edit any vote Value

### ISSUE THREAD

**Issue by overcrash66** [AndyRixon/LayerBB#52]
### Expected Behaviour: 
User not allowed to edit vote value .
### Actual Behaviour:
File: **thread.php**
Poll value inside a form (a Java script form)
User can change the value of the radio button (to any other value)
**Result:** New value will be accepted and registered in database . 
### Steps to Reproduce Issue:
1-log in or create a new account 
2-create a new thread with a poll (a vote)
3-inspect any answer (radio button element) and change his value
4-click 'vote now!'

**Comment by AndyRixon** [comment]
Due a new version being developed. We will not be adding features to Version 1.x
