### ISSUE TITLE
404 missing page (https://forum.layerbb.com/members.php/cmd/signin)

### ISSUE THREAD

**Issue by HarryAdney** [AndyRixon/LayerBB#53]
### Expected Behaviour
See the login page

### Actual Behaviour
404 error

### Steps to Reproduce Issue
Go to https://forum.layerbb.com/members.php/cmd/signin in browser, or login via the modal on https://forum.layerbb.com/forum.php

### Server Environment (PHP, MySQL, Apache Version and Operating System)
Windows 10 Pro Insider, Chrome version 79.0.3945.130 (Official Build) (64-bit)

**Comment by KarlBrittain** [comment]
Thank you for the report. However as we have Version 2 in development which can be previewed on our website. We will no longer be releasing any fixes for Version 1.x.

Best Regards
LayerBB Project Management

**Comment by HarryAdney** [comment]
It would be a good idea to either redirect visitors to the preview site or at least update the v1 page to show that the version 1 login no longer works.

**Comment by KarlBrittain** [comment]
We are in the process of fixing the issue on our website, but the fix won't be made public. I believe this to be a local server issue and not a software issue.

**Comment by KarlBrittain** [comment]
This has now been resolved. This was due to our server configuration.

**Comment by HarryAdney** [comment]
;)
