### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by jakesullyneytiri** [AndyRixon/LayerBB#6]
Just tried on the forum at layerbb.com and own installation copy of beta 4 both are giving empty page after submitting forgot password.

**Comment by ghost** [comment]
Found the issue and fixed the issue, but come across another issue which is a missing file, which I have to now go through and try to recreate the file.

**Comment by jakesullyneytiri** [comment]
haha well good that this, made you find more bugs :)

**Comment by ghost** [comment]
This is now completely fixed and will be available in the next version.
